language: python
python:
    - "2.7"
    - "3.3"

before_install: 
    - sudo apt-get install -qq python-numpy python-scipy

install: sudo python setup.py install

script: python frame_learn/_test/_test.py
